[package]
name = "zome_utils"
version = "0.0.1"
edition = "2021"

[lib]
name = "zome_utils"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = { version = "1.0", default-features = false }

hdk = { version = "0.0.122", default-features = false }
holo_hash = { version = "=0.0.19", default-features = false, features = ["encoding"] }
